version: '3.7'

services:
  spark-master:
    image: apache/spark:3.5.1
    container_name: spark-master
    user: root
    command: ["/bin/bash", "-c", "apt-get update && apt-get install -y python3 python3-pip && pip3 install cassandra-driver pyspark==3.5.1 && /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master"]
    ports:
      - "9090:8080"
      - "7077:7077"
    networks:
      - kafka_confluent
    volumes:
      - /home/diin/HocKi_8/BigDATA/Project_Kafka/spark_stream.py:/opt/spark/spark_stream.py
      - /home/diin/HocKi_8/BigDATA/Project_Kafka/docker/spark/jars/spark-cassandra-connector-assembly_2.12-3.5.1.jar:/opt/spark/jars/spark-cassandra-connector-assembly_2.12-3.5.1.jar
      - /home/diin/HocKi_8/BigDATA/Project_Kafka/docker/spark/jars/spark-sql-kafka-0-10_2.12-3.5.1.jar:/opt/spark/jars/spark-sql-kafka-0-10_2.12-3.5.1.jar
      - /home/diin/HocKi_8/BigDATA/Project_Kafka/docker/spark/jars/spark-streaming-kafka-0-10-assembly_2.12-3.5.1.jar:/opt/spark/jars/spark-streaming-kafka-0-10-assembly_2.12-3.5.1.jar
      - /home/diin/HocKi_8/BigDATA/Project_Kafka/docker/spark/jars/kafka-clients-3.5.1.jar:/opt/spark/jars/kafka-clients-3.5.1.jar
      - /home/diin/HocKi_8/BigDATA/Project_Kafka/docker/spark/jars/commons-pool2-2.11.1.jar:/opt/spark/jars/commons-pool2-2.11.1.jar
      - /home/diin/HocKi_8/BigDATA/Project_Kafka/docker/spark/jars/spark-token-provider-kafka-0-10_2.12-3.5.1.jar:/opt/spark/jars/spark-token-provider-kafka-0-10_2.12-3.5.1.jar
  
  spark-worker:
    image: apache/spark:3.5.1
    container_name: spark-worker
    user: root
    command: ["/bin/bash", "-c", "apt-get update && apt-get install -y python3 python3-pip && pip3 install cassandra-driver pyspark==3.5.1 && /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077"]
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 4
      SPARK_WORKER_MEMORY: 4g
      SPARK_MASTER_URL: spark://spark-master:7077
    depends_on:
      - spark-master
    networks:
      - kafka_confluent
    volumes:
      - /home/diin/HocKi_8/BigDATA/Project_Kafka/spark_stream.py:/opt/spark/spark_stream.py
      - /home/diin/HocKi_8/BigDATA/Project_Kafka/docker/spark/jars/spark-cassandra-connector-assembly_2.12-3.5.1.jar:/opt/spark/jars/spark-cassandra-connector-assembly_2.12-3.5.1.jar
      - /home/diin/HocKi_8/BigDATA/Project_Kafka/docker/spark/jars/spark-sql-kafka-0-10_2.12-3.5.1.jar:/opt/spark/jars/spark-sql-kafka-0-10_2.12-3.5.1.jar
      - /home/diin/HocKi_8/BigDATA/Project_Kafka/docker/spark/jars/spark-streaming-kafka-0-10-assembly_2.12-3.5.1.jar:/opt/spark/jars/spark-streaming-kafka-0-10-assembly_2.12-3.5.1.jar
      - /home/diin/HocKi_8/BigDATA/Project_Kafka/docker/spark/jars/kafka-clients-3.5.1.jar:/opt/spark/jars/kafka-clients-3.5.1.jar
      - /home/diin/HocKi_8/BigDATA/Project_Kafka/docker/spark/jars/commons-pool2-2.11.1.jar:/opt/spark/jars/commons-pool2-2.11.1.jar
      - /home/diin/HocKi_8/BigDATA/Project_Kafka/docker/spark/jars/spark-token-provider-kafka-0-10_2.12-3.5.1.jar:/opt/spark/jars/spark-token-provider-kafka-0-10_2.12-3.5.1.jar
networks:
  kafka_confluent:
    external: true